resources:
  - ../../base

namePrefix: dev-

commonLabels:
  type: dev-demo
  app: dev-foo
  org: Corporation

commonAnnotations:
  note: Hello, I am development!


images:
  # images.name defines the images name which will be replaced
  - name: mikehsu0618/api-service
    newTag: development

patches:
  # patchJson6902, patchesStrategicMerge are both deprecated in future
  - patch: |
      - op: replace
        path: /metadata/name
        value: the-dev-development
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: the-dev-container
    target:
      # group, kind, version can think of apiVersion is optional, ex: apps/v1
      group: apps
      kind: Deployment
      version: v1
      name: foo-deployment-v1