apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello
  test: test

resources:
  - deployment.yaml
  - service.yaml
  - configMap.yaml