apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    - default:
        cpu: 1000m
        memory: 500Mi
      defaultRequest:
        cpu: 500m
        memory: 200Mi
      type: Container