namePrefix: development-
nameSuffix: -v2

namespace: development-namesapce

commonLabels:
  app: Production-hello
  variant: Production
  org: acmeCorporation

commonAnnotations:
  note: Hello, I am Production!

resources:
  - ../../base

patchesStrategicMerge:
  - configMap.yaml

images:
  # images.name defines the images name which will be replaced
  - name: monopole/hello
    newName: monopole/hello
    newTag: development
patches:
  - patch: |
      - op: replace
        path: /metadata/name
        value: the-deployment-production
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: the-container-production
    target:
      # group, version can think of apiVersion is optional, ex: apps/v1
      group: apps
      kind: Deployment
      version: v1
      name: the-deployment